# Generated by Django 5.0.6 on 2024-06-20 13:53

import django.db.models.deletion
import django.utils.timezone
import eco_hunter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropsImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=256, null=True)),
                ('logo_organisation', models.ImageField(null=True, upload_to=eco_hunter.models.get_upload_path_logo)),
                ('organisation_link', models.CharField(max_length=256, null=True)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Requestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256)),
                ('address', models.CharField(max_length=512)),
                ('description', models.CharField(default='-', max_length=512)),
                ('latitude', models.FloatField(default=1.1, max_length=128)),
                ('longitude', models.FloatField(default=1.1, max_length=128)),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('pred_status', models.CharField(max_length=32, null=True)),
                ('fraction_status_danger', models.CharField(max_length=128, null=True)),
                ('fraction_status_nondanger', models.CharField(max_length=128, null=True)),
                ('img', models.ImageField(upload_to=eco_hunter.models.get_upload_path_img)),
            ],
        ),
        migrations.CreateModel(
            name='RequisitionImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=eco_hunter.models.get_upload_path)),
                ('img_with_boxes_seg', models.ImageField(null=True, upload_to=eco_hunter.models.get_upload_path_boxes)),
                ('img_with_boxes_det', models.ImageField(null=True, upload_to=eco_hunter.models.get_upload_path_boxes)),
                ('cls_predict', models.IntegerField(max_length=8, null=True)),
                ('predicted_danger_item', models.IntegerField(null=True)),
                ('predicted_nondanger_item', models.IntegerField(null=True)),
                ('requisition_img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_hunter.requestion')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holding_date', models.DateTimeField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(default='', max_length=100)),
                ('text', models.TextField(default='', max_length=2000)),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eco_hunter.organisation')),
                ('requisition_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eco_hunter.requestion')),
            ],
        ),
    ]
