# Generated by Django 5.0.6 on 2024-06-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_hunter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CropsImg',
        ),
    ]
