# Generated by Django 5.0.6 on 2024-06-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_hunter', '0002_delete_cropsimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionimg',
            name='cls_predict',
            field=models.IntegerField(null=True),
        ),
    ]
