# Generated by Django 5.0.6 on 2024-06-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eco_hunter', '0003_alter_requisitionimg_cls_predict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestion',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
    ]
