# Generated by Django 5.0.6 on 2024-06-21 11:09

import eco_hunter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_hunter', '0004_alter_requestion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionimg',
            name='cls_predict',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionimg',
            name='img_with_boxes_det',
            field=models.ImageField(default=None, null=True, upload_to=eco_hunter.models.get_upload_path_boxes),
        ),
        migrations.AlterField(
            model_name='requisitionimg',
            name='img_with_boxes_seg',
            field=models.ImageField(default=None, null=True, upload_to=eco_hunter.models.get_upload_path_boxes),
        ),
        migrations.AlterField(
            model_name='requisitionimg',
            name='predicted_danger_item',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='requisitionimg',
            name='predicted_nondanger_item',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
