# Generated by Django 5.0.6 on 2024-06-22 19:04

import eco_hunter.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_hunter', '0005_alter_requisitionimg_cls_predict_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisitionimg',
            name='img_with_boxes_det',
            field=models.ImageField(default=None, upload_to=eco_hunter.models.get_upload_path_boxes),
        ),
        migrations.AlterField(
            model_name='requisitionimg',
            name='img_with_boxes_seg',
            field=models.ImageField(default=None, upload_to=eco_hunter.models.get_upload_path_boxes),
        ),
    ]
