# Generated by Django 5.0.6 on 2024-06-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_hunter', '0007_alter_requisitionimg_img_with_boxes_det_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestion',
            name='fraction_status_danger',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='fraction_status_nondanger',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='pred_status',
            field=models.CharField(default='', max_length=32, null=True),
        ),
    ]
