# Generated by Django 5.0.6 on 2024-06-23 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_hunter', '0008_alter_requestion_fraction_status_danger_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organisation',
            options={'verbose_name': 'Организаця', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='requisitionimg',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterField(
            model_name='requestion',
            name='address',
            field=models.CharField(max_length=512, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обращения'),
        ),
    ]
