# Generated by Django 5.0.6 on 2024-06-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eco_hunter', '0009_alter_organisation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestion',
            name='address',
            field=models.CharField(max_length=512, verbose_name='Адрес свалки'),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='description',
            field=models.CharField(default='-', max_length=512, verbose_name='Описание места свалки'),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='fraction_status_danger',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='Опасной фракции'),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='fraction_status_nondanger',
            field=models.CharField(default='', max_length=128, null=True, verbose_name='Безопасной фракции'),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='latitude',
            field=models.FloatField(default=1.1, max_length=128, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='longitude',
            field=models.FloatField(default=1.1, max_length=128, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Имя отправителя'),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='requestion',
            name='pred_status',
            field=models.CharField(default='', max_length=32, null=True, verbose_name='0-опасные|1-не опасные отходы'),
        ),
    ]
